# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frb_sifter.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'frb_sifter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66rb_sifter.proto\"\xa2\x01\n\rConfigMessage\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x13\n\x0bpirate_yaml\x18\x02 \x01(\t\x12\x14\n\x0cxengine_yaml\x18\x03 \x01(\t\x12\x1e\n\x16\x64\x65\x64ispersion_plan_yaml\x18\x04 \x01(\t\x12\x14\n\x0cgrouper_yaml\x18\x05 \x01(\t\x12\x16\n\x0esearch_ip_addr\x18\x06 \x01(\t\"\x19\n\x0b\x43onfigReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\xaa\x01\n\x08\x46rbEvent\x12\x0f\n\x07\x62\x65\x61m_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x66pga_timestamp\x18\x02 \x01(\x03\x12\n\n\x02\x64m\x18\x03 \x01(\x02\x12\x0b\n\x03snr\x18\x04 \x01(\x02\x12\x10\n\x08rfi_prob\x18\x05 \x01(\x02\x12\x10\n\x08width_ms\x18\x06 \x01(\x02\x12\x1b\n\x13subband_freq_lo_MHz\x18\x07 \x01(\x02\x12\x1b\n\x13subband_freq_hi_MHz\x18\x08 \x01(\x02\"\xa5\x01\n\x10\x46rbEventsMessage\x12\x16\n\x0e\x66rom_simulator\x18\x01 \x01(\x08\x12\x13\n\x0b\x62\x65\x61m_set_id\x18\x02 \x01(\x05\x12\x18\n\x10\x63hunk_fpga_start\x18\x03 \x01(\x03\x12\x16\n\x0e\x63hunk_fpga_end\x18\x04 \x01(\x03\x12\x19\n\x06\x65vents\x18\x05 \x03(\x0b\x32\t.FrbEvent\x12\x17\n\x0f\x63oarsegrain_snr\x18\x06 \x03(\x02\"-\n\x0e\x46rbEventsReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*Q\n\x0fProtocolVersion\x12 \n\x1cPROTOCOL_VERSION_UNSPECIFIED\x10\x00\x12\x1c\n\x18PROTOCOL_VERSION_CURRENT\x10\x03\x32t\n\tFrbSifter\x12\x34\n\x12\x43heckConfiguration\x12\x0e.ConfigMessage\x1a\x0c.ConfigReply\"\x00\x12\x31\n\tFrbEvents\x12\x11.FrbEventsMessage\x1a\x0f.FrbEventsReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frb_sifter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROTOCOLVERSION']._serialized_start=600
  _globals['_PROTOCOLVERSION']._serialized_end=681
  _globals['_CONFIGMESSAGE']._serialized_start=21
  _globals['_CONFIGMESSAGE']._serialized_end=183
  _globals['_CONFIGREPLY']._serialized_start=185
  _globals['_CONFIGREPLY']._serialized_end=210
  _globals['_FRBEVENT']._serialized_start=213
  _globals['_FRBEVENT']._serialized_end=383
  _globals['_FRBEVENTSMESSAGE']._serialized_start=386
  _globals['_FRBEVENTSMESSAGE']._serialized_end=551
  _globals['_FRBEVENTSREPLY']._serialized_start=553
  _globals['_FRBEVENTSREPLY']._serialized_end=598
  _globals['_FRBSIFTER']._serialized_start=683
  _globals['_FRBSIFTER']._serialized_end=799
# @@protoc_insertion_point(module_scope)
