# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frb_sifter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'frb_sifter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66rb_sifter.proto\"\x1d\n\rConfigMessage\x12\x0c\n\x04yaml\x18\x01 \x01(\t\"\x19\n\x0b\x43onfigReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"p\n\x08\x46rbEvent\x12\x0f\n\x07\x62\x65\x61m_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x66pga_timestamp\x18\x02 \x01(\x03\x12\n\n\x02\x64m\x18\x03 \x01(\x02\x12\x10\n\x08\x64m_error\x18\x04 \x01(\x02\x12\x0b\n\x03snr\x18\x05 \x01(\x02\x12\x10\n\x08rfi_prob\x18\x06 \x01(\x02\"t\n\x10\x46rbEventsMessage\x12\x16\n\x0ehas_injections\x18\x01 \x01(\x08\x12\x13\n\x0b\x62\x65\x61m_set_id\x18\x02 \x01(\x05\x12\x18\n\x10\x63hunk_fpga_count\x18\x03 \x01(\x03\x12\x19\n\x06\x65vents\x18\x04 \x03(\x0b\x32\t.FrbEvent\"-\n\x0e\x46rbEventsReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2t\n\tFrbSifter\x12\x34\n\x12\x43heckConfiguration\x12\x0e.ConfigMessage\x1a\x0c.ConfigReply\"\x00\x12\x31\n\tFrbEvents\x12\x11.FrbEventsMessage\x1a\x0f.FrbEventsReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frb_sifter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGMESSAGE']._serialized_start=20
  _globals['_CONFIGMESSAGE']._serialized_end=49
  _globals['_CONFIGREPLY']._serialized_start=51
  _globals['_CONFIGREPLY']._serialized_end=76
  _globals['_FRBEVENT']._serialized_start=78
  _globals['_FRBEVENT']._serialized_end=190
  _globals['_FRBEVENTSMESSAGE']._serialized_start=192
  _globals['_FRBEVENTSMESSAGE']._serialized_end=308
  _globals['_FRBEVENTSREPLY']._serialized_start=310
  _globals['_FRBEVENTSREPLY']._serialized_end=355
  _globals['_FRBSIFTER']._serialized_start=357
  _globals['_FRBSIFTER']._serialized_end=473
# @@protoc_insertion_point(module_scope)
