# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import frb_sifter_pb2 as frb__sifter__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in frb_sifter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrbSifterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckConfiguration = channel.unary_unary(
                '/FrbSifter/CheckConfiguration',
                request_serializer=frb__sifter__pb2.ConfigMessage.SerializeToString,
                response_deserializer=frb__sifter__pb2.ConfigReply.FromString,
                _registered_method=True)
        self.FrbEvents = channel.unary_unary(
                '/FrbSifter/FrbEvents',
                request_serializer=frb__sifter__pb2.FrbEventsMessage.SerializeToString,
                response_deserializer=frb__sifter__pb2.FrbEventsReply.FromString,
                _registered_method=True)


class FrbSifterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckConfiguration(self, request, context):
        """First call - report my configuration.
        Returns true if good, false otherwise.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FrbEvents(self, request, context):
        """?? For injections only
        rpc NewBeamSet (BeamSetUpdateMessage) returns (BeamSetUpdateReply) {}

        Report events from a given time chunk.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrbSifterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckConfiguration,
                    request_deserializer=frb__sifter__pb2.ConfigMessage.FromString,
                    response_serializer=frb__sifter__pb2.ConfigReply.SerializeToString,
            ),
            'FrbEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.FrbEvents,
                    request_deserializer=frb__sifter__pb2.FrbEventsMessage.FromString,
                    response_serializer=frb__sifter__pb2.FrbEventsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FrbSifter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FrbSifter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrbSifter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrbSifter/CheckConfiguration',
            frb__sifter__pb2.ConfigMessage.SerializeToString,
            frb__sifter__pb2.ConfigReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FrbEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrbSifter/FrbEvents',
            frb__sifter__pb2.FrbEventsMessage.SerializeToString,
            frb__sifter__pb2.FrbEventsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
