"""allow pirate_config to be null

Revision ID: 26a9940610b0
Revises: c1a9cb0593d4
Create Date: 2026-07-21 20:30:33.516394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a9940610b0'
down_revision: Union[str, None] = 'c1a9cb0593d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pirate_config', 'pirate_config',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pirate_config', 'pirate_config',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
