"""add IntensityFile db model (2)

Revision ID: 2c3de05ceacc
Revises: 70aefb09dfe9
Create Date: 2026-08-25 19:27:09.850223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c3de05ceacc'
down_revision: Union[str, None] = '70aefb09dfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
