"""reorg is_X columns (defaults)

Revision ID: 343b5a25fd9d
Revises: 7e6237cff352
Create Date: 2024-06-11 19:12:50.661036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343b5a25fd9d'
down_revision: Union[str, None] = '7e6237cff352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_known_pulsar', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('event', sa.Column('is_new_burst', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('event', 'is_known')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_known', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('event', 'is_new_burst')
    op.drop_column('event', 'is_known_pulsar')
    # ### end Alembic commands ###
