"""set more columns optional

Revision ID: 523bf92070bc
Revises: 0f5d47b5a840
Create Date: 2024-06-11 14:36:45.490728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523bf92070bc'
down_revision: Union[str, None] = '0f5d47b5a840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'dm',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'dm_error',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'ra',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'ra_error',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'dec',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'dec_error',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'dm_ne2001',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'dm_ymw2016',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'spectral_index',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'scattering',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'fluence',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'flux',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('event', 'pulse_width',
               existing_type=sa.REAL(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'pulse_width',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'flux',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'fluence',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'scattering',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'spectral_index',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'dm_ymw2016',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'dm_ne2001',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'dec_error',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'dec',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'ra_error',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'ra',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'dm_error',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('event', 'dm',
               existing_type=sa.REAL(),
               nullable=False)
    # ### end Alembic commands ###
