"""add rfi_grade, beam_activity

Revision ID: 6793bd1ef4d3
Revises: 55302a422669
Create Date: 2024-06-11 14:23:59.595159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6793bd1ef4d3'
down_revision: Union[str, None] = '55302a422669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('rfi_grade', sa.REAL(), nullable=False))
    op.add_column('event', sa.Column('beam_activity', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'beam_activity')
    op.drop_column('event', 'rfi_grade')
    # ### end Alembic commands ###
