"""add IntensityFile db model

Revision ID: 6f353d928e1f
Revises: 2c3de05ceacc
Create Date: 2026-08-25 20:22:04.541517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f353d928e1f'
down_revision: Union[str, None] = '2c3de05ceacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intensity_file', sa.Column('failed', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('intensity_file', 'error_message',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intensity_file', 'error_message',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('intensity_file', 'failed')
    # ### end Alembic commands ###
