"""make known_source fields optional

Revision ID: 6fcb9558c619
Revises: 8cb7c14dbe50
Create Date: 2024-06-11 19:51:52.200939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcb9558c619'
down_revision: Union[str, None] = '8cb7c14dbe50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('known_source', 'ra',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('known_source', 'dec',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('known_source', 'dm',
               existing_type=sa.REAL(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('known_source', 'dm',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('known_source', 'dec',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('known_source', 'ra',
               existing_type=sa.REAL(),
               nullable=False)
    # ### end Alembic commands ###
