"""add IntensityFile db model

Revision ID: 70aefb09dfe9
Revises: 26a9940610b0
Create Date: 2026-08-25 19:24:37.916531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70aefb09dfe9'
down_revision: Union[str, None] = '26a9940610b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intensity_file',
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intensity_file')
    # ### end Alembic commands ###
