"""add is_repeating_frb

Revision ID: 8cb7c14dbe50
Revises: 343b5a25fd9d
Create Date: 2024-06-11 19:25:46.089681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb7c14dbe50'
down_revision: Union[str, None] = '343b5a25fd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_repeating_frb', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'is_repeating_frb')
    # ### end Alembic commands ###
