"""add initial models

Revision ID: 932121853062
Revises: 
Create Date: 2024-09-16 15:11:46.607275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932121853062'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dumb_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('known_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ra', sa.REAL(), nullable=True),
    sa.Column('dec', sa.REAL(), nullable=True),
    sa.Column('dm', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Double(), nullable=True),
    sa.Column('is_rfi', sa.Boolean(), nullable=False),
    sa.Column('is_known_pulsar', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_new_burst', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_frb', sa.Boolean(), nullable=False),
    sa.Column('is_repeating_frb', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rfi_grade', sa.REAL(), nullable=False),
    sa.Column('beam_activity', sa.SmallInteger(), nullable=False),
    sa.Column('best_beam', sa.SmallInteger(), nullable=True),
    sa.Column('nbeams', sa.SmallInteger(), nullable=False),
    sa.Column('best_snr', sa.REAL(), nullable=True),
    sa.Column('total_snr', sa.REAL(), nullable=True),
    sa.Column('dm', sa.REAL(), nullable=True),
    sa.Column('dm_error', sa.REAL(), nullable=True),
    sa.Column('ra', sa.REAL(), nullable=True),
    sa.Column('ra_error', sa.REAL(), nullable=True),
    sa.Column('dec', sa.REAL(), nullable=True),
    sa.Column('dec_error', sa.REAL(), nullable=True),
    sa.Column('dm_ne2001', sa.REAL(), nullable=True),
    sa.Column('dm_ymw2016', sa.REAL(), nullable=True),
    sa.Column('spectral_index', sa.REAL(), nullable=True),
    sa.Column('scattering', sa.REAL(), nullable=True),
    sa.Column('fluence', sa.REAL(), nullable=True),
    sa.Column('flux', sa.REAL(), nullable=True),
    sa.Column('pulse_width', sa.REAL(), nullable=True),
    sa.Column('known_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['known_id'], ['known_source.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_beam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beam', sa.Integer(), nullable=False),
    sa.Column('snr', sa.REAL(), nullable=False),
    sa.Column('timestamp_utc', sa.Double(), nullable=False),
    sa.Column('timestamp_fpga', sa.Integer(), nullable=False),
    sa.Column('time_error', sa.REAL(), nullable=False),
    sa.Column('tree_index', sa.Integer(), nullable=False),
    sa.Column('rfi_grade', sa.Integer(), nullable=False),
    sa.Column('rfi_mask_fraction', sa.REAL(), nullable=False),
    sa.Column('rfi_clip_fraction', sa.REAL(), nullable=False),
    sa.Column('dm', sa.REAL(), nullable=False),
    sa.Column('dm_error', sa.REAL(), nullable=False),
    sa.Column('ra', sa.REAL(), nullable=False),
    sa.Column('ra_error', sa.REAL(), nullable=False),
    sa.Column('dec', sa.REAL(), nullable=False),
    sa.Column('dec_error', sa.REAL(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_beam')
    op.drop_table('event')
    op.drop_table('known_source')
    op.drop_table('dumb_test')
    # ### end Alembic commands ###
