"""add initial models

Revision ID: ae3b20fc0986
Revises: 
Create Date: 2024-06-10 15:07:21.856138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3b20fc0986'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Double(), nullable=False),
    sa.Column('is_rfi', sa.Boolean(), nullable=False),
    sa.Column('is_known', sa.Boolean(), nullable=False),
    sa.Column('is_frb', sa.Boolean(), nullable=False),
    sa.Column('best_beam', sa.SmallInteger(), nullable=False),
    sa.Column('nbeams', sa.SmallInteger(), nullable=False),
    sa.Column('best_snr', sa.Float(), nullable=False),
    sa.Column('total_snr', sa.Float(), nullable=False),
    sa.Column('dm', sa.Float(), nullable=False),
    sa.Column('dm_error', sa.Float(), nullable=False),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('ra_error', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('dec_error', sa.Float(), nullable=False),
    sa.Column('dm_ne2001', sa.Float(), nullable=False),
    sa.Column('dm_ymw2016', sa.Float(), nullable=False),
    sa.Column('spectral_index', sa.Float(), nullable=False),
    sa.Column('scattering', sa.Float(), nullable=False),
    sa.Column('fluence', sa.Float(), nullable=False),
    sa.Column('flux', sa.Float(), nullable=False),
    sa.Column('pulse_width', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('known_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('dm', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_beam',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('beam', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_beam')
    op.drop_table('known_source')
    op.drop_table('event')
    # ### end Alembic commands ###
