"""add PirateConfig and BeamSNR

Revision ID: c1a9cb0593d4
Revises: ba192e91cc86
Create Date: 2026-05-20 15:24:18.342889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a9cb0593d4'
down_revision: Union[str, None] = 'ba192e91cc86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
